# Makefile for pal for linux

HOST_PROJ_ROOT ?= $(shell pwd)/../../..
include $(HOST_PROJ_ROOT)/Makefile.defs
TARGET_LIBS = pal_linux
PLAT_OS=linux
include ../project_pal.mk

include $(HOST_PROJ_ROOT)/Makefile.rules

