# Makefile for cmpu utility
HOST_PROJ_ROOT ?= $(shell pwd)/../../..
include $(HOST_PROJ_ROOT)/Makefile.defs
#overwriting the OS defined in the config
OS = no_os
export

include project_cmpu.mk

include $(HOST_PROJ_ROOT)/Makefile.rules

